// MODIFICA ESTA URL POR LA DEL SERVICIO WEB DESPUES DE HABERLO DESPLEGADO
const AS_URL_BASE = "https://script.google.com/macros/s/AKfycbxNRfWb8-MWFBBm6MuW-uITLgAQ9nkeoM0WI2weJoC35wEG5eaFAhi2KUS2dh_lGTESbw/exec";
